
name : "Terraform-manual-actions"

on:
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
  
     

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

  apply:
    name: 'apply'
    runs-on: ubuntu-latest
    needs: plan
    environment:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
      name: Apply_Approval
        # As prod-env required reviewers is `dineshba`,
        # it will wait for approval from dineshba
        

    steps:
    #... checkout, setup, init terraform steps like plan
    - name: Terraform apply
      run: terraform apply  
