name : "Terraform-Plan-manual-actions"

on:
# workflow_dispatch
  push:
    branches:
    - "dev" 
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
     environment:
         - dev
         - prod

      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
     
      

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: aws_s3.tf
      run: |
        terraform init
        terraform workspace new ${{env.environment}}
        terraform workspace select ${{env.environment}} $$ terraform plan
        terraform workspace select ${{env.environment}} $$ terraform apply

  
    # Generates an execution plan for Terraform
  #  - name: Terraform Plan
  #    run: terraform plan -input=false
